### ISSUE TITLE
Merge hashicorp vault with develop branch

### ISSUE THREAD

**Issue by mtoof** [abbastoof/transcendence#23]
**Branch Name:** ```refactor/023-merge-hashicorp-vault-with-develop```

**Description:**
Merge Hashicorp Vault branch with Develop branch

hashicorp-vault branch has been created to integrate Hashicorp Vault with the application. The branch has been tested and is ready to be merged with the Develop branch. The services have been updated to fetch the secrets from Hashicorp Vault. The branch is ready to be merged with the Develop branch.

hashiCorp-vault branch -> `feature/hashiCorp-vault`

**Tasks:**

- [x] Clone the repo on your system then switch to `develop` branch and pull from `feature/hashiCorp-vault`
- [x] Merge Hashicorp Vault with Develop branch
- [x] Add all the secrets or password in services to the Hashicorp Vault
- [x] Update the services to fetch the secrets from Hashicorp Vault
- [ ] Test the application
- [x] Resolve any conflicts
- [x] Push the changes
